### ISSUE TITLE
As-is addon contains invalid transport

### ISSUE THREAD

**Issue by hvheuver** [fioritracker/installation#3]
We are trying to set up the app, however we recieve the following error:
"RFC works but FM not available (check if Add-on for As-is information is installed" in the "Managed Systems" tile. 
We tried to install the Add-on (https://github.com/fioritracker/installation/tree/master/Managed-systems%5BGateway%5D/As-is-info-Add-on), but the transport seems to be invalid and throws errors when trying to import it into the system:
![image](https://user-images.githubusercontent.com/22474063/86234754-b5a27480-bb97-11ea-8b38-7b4774aaf0c4.png)

Could the transport be reviewed?

**Comment by fioritracker** [comment]
The corrupted file is fixed and now it's should be correct: https://github.com/fioritracker/installation/tree/master/Managed-systems%5BGateway%5D/As-is-info-Add-on/data

**Comment by hvheuver** [comment]
Thanks for looking into the issue. We are able to put the transport in the transport queue, but we are still not able to import the request. Return code is now 12. 

Our basis expert referred me to note https://launchpad.support.sap.com/#/notes/1616269 and that there might be something wrong with the cofile. 

We receive the following error: **Transfer order does not exist**

When we try to open the Task/Request, it gives us the error that it does not exist on our system.

The other transports, NPLK900759 and NPLK900762 can be imported without issues, but this one seems to still cause an issue.

**Comment by fioritracker** [comment]
Please make sure you have downloaded all the files as a complete repository in one zip archive. We have noticed that downloading K files separately results in a changed file.
